typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)

typeset -g POWERLEVEL9K_BACKGROUND=black
typeset -g POWERLEVEL9K_FOREGROUND='#c1c1c1'

typeset -g POWERLEVEL9K_DIR_BACKGROUND=black
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#5f8787'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#5f8787'
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

typeset -g POWERLEVEL9K_VCS_BACKGROUND=black
typeset -g POWERLEVEL9K_VCS_FOREGROUND='#9e9e9e'
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
typeset -g POWERLEVEL9K_VCS_MODIFIED_ICON='*'

typeset -g POWERLEVEL9K_TIME_BACKGROUND=black
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#5f8787'
typeset -g POWERLEVEL9K_TIME_FORMAT='%I:%M %p'
typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true

typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '

typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{#5f8787}❯%f '
