set -g status-bg '#000000'
set -g status-fg '#c1c1c1'
set -g status-left '#[fg=#7799bb,bold]#S #[default]'
set -g status-right '#[fg=#556677]#($HOME/dotfiles/tmux/network.sh) #[fg=#444444]%a %d %b #[fg=#c1c1c1]%I:%M %p'
set -g window-status-style 'fg=#444444,bg=default'
set -g window-status-format '#[fg=#444444]#I #[fg=#444444]#W'
set -g window-status-current-style 'fg=#c1c1c1,bg=#121212,bold'
set -g window-status-current-format '#[fg=#7799bb,bg=#121212] #I:#W #[default]'
set -g pane-border-style 'fg=#333333'
set -g pane-active-border-style 'fg=#5f8787'
set -g message-style 'fg=#c1c1c1,bg=#121212'
set -g message-command-style 'fg=#c1c1c1,bg=#121212'
setw -g mode-style 'fg=#000000,bg=#7799bb'
