set -g status-bg '#101113'
set -g status-fg '#9f9e99'
set -g status-left '#[fg=#7a837c,bold]#S #[default]'
set -g status-right '#[fg=#697a9a]#($HOME/dotfiles/tmux/network.sh) #[fg=#554a62]%a %d %b #[fg=#9f9e99]%I:%M %p'
set -g window-status-style 'fg=#554a62,bg=default'
set -g window-status-format '#[fg=#554a62]#I #[fg=#554a62]#W'
set -g window-status-current-style 'fg=#9f9e99,bg=#161719,bold'
set -g window-status-current-format '#[fg=#93554b,bg=#161719] #I:#W #[default]'
set -g pane-border-style 'fg=#554a62'
set -g pane-active-border-style 'fg=#697a9a'
set -g message-style 'fg=#9f9e99,bg=#161719'
set -g message-command-style 'fg=#9f9e99,bg=#161719'
setw -g mode-style 'fg=#101113,bg=#ac7f7b'
