set -g status-bg '#1f1f28'
set -g status-fg '#dcd7ba'
set -g status-left '#[fg=#7fb4ca,bold]#S #[default]'
set -g status-right '#[fg=#7e9cd8]#($HOME/dotfiles/tmux/network.sh) #[fg=#727169]%a %d %b #[fg=#dcd7ba]%I:%M %p'
set -g window-status-style 'fg=#727169,bg=default'
set -g window-status-format '#[fg=#727169]#I #[fg=#727169]#W'
set -g window-status-current-style 'fg=#dcd7ba,bg=#2a2a37,bold'
set -g window-status-current-format '#[fg=#e46876,bg=#2a2a37] #I:#W #[default]'
set -g pane-border-style 'fg=#2a2a37'
set -g pane-active-border-style 'fg=#7e9cd8'
set -g message-style 'fg=#dcd7ba,bg=#2a2a37'
set -g message-command-style 'fg=#dcd7ba,bg=#2a2a37'
setw -g mode-style 'fg=#1f1f28,bg=#e6c384'
