set -g status-bg '#000000'
set -g status-fg '#ffffff'
set -g status-left '#[fg=#c0c0c0,bold]#S #[default]'
set -g status-right '#[fg=#999999]#($HOME/dotfiles/tmux/network.sh) #[fg=#6b6b6b]%a %d %b #[fg=#ffffff]%I:%M %p'
set -g window-status-style 'fg=#6b6b6b,bg=default'
set -g window-status-format '#[fg=#6b6b6b]#I #[fg=#6b6b6b]#W'
set -g window-status-current-style 'fg=#ffffff,bg=#1a1a1a,bold'
set -g window-status-current-format '#[fg=#6b6b6b,bg=#1a1a1a] #I:#W #[default]'
set -g pane-border-style 'fg=#2e2e2e'
set -g pane-active-border-style 'fg=#999999'
set -g message-style 'fg=#ffffff,bg=#1a1a1a'
set -g message-command-style 'fg=#ffffff,bg=#1a1a1a'
setw -g mode-style 'fg=#000000,bg=#b3b3b3'
