# Rose Pine
# base:    #191724
# text:    #e0def4
# subtle:  #908caa
# love:    #eb6f92
# surface: #1f1d2e

general {
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = $HOME/Pictures/greekwp.png
    blur_passes = 2
    blur_size = 4
    brightness = 0.7
}

image {
    monitor = eDP-1
    path = $HOME/Pictures/ava.jpeg
    size = 200
    rounding = 0
    border_size = 0
    position = 0, 0
    halign = center
    valign = center
}

input-field {
    monitor = eDP-1
    size = 280, 48
    position = 0, -140
    halign = center
    valign = center
    dots_size = 0.25
    dots_spacing = 0.3
    rounding = -1

    outline_thickness = 2
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = rgb(e0def4)
    check_color = rgba(0, 0, 0, 0)
    fail_color = rgb(eb6f92)

    fade_on_empty = true
    placeholder_text =
    hide_input = false
    fail_text = KURWA WRONG
}

label {
    monitor = eDP-1
    text = $TIME12
    #text = cmd[update:1000] echo "$(date +"%I:%M %p")"
    color = rgb(e0def4)
    font_size = 64
    font_family = Iosevka Nerd Font Mono
    position = 0, 170
    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    color = rgb(908caa)
    font_size = 14
    font_family = Iosevka Nerd Font Mono
    position = 0, 120
    halign = center
    valign = center
}
