theme = "guts"
# theme = "traffic"
# theme = "monotheme"
# theme = "forest-blue"
# theme = "rose-pine"
# theme = "kanagawa-wave"
# theme = "black metal (gorgoroth)"
background-opacity = 0.95
background-blur-radius = 20
