" leader
let mapleader = " "
" config dir
execute 'set runtimepath^=' . fnameescape(expand('~/dotfiles/vim'))
" plugins
call plug#begin(expand('~/dotfiles/vim/plugged'))
	Plug 'utensils/colors.vim'
call plug#end()
" basics
set nocompatible
filetype plugin on
filetype indent on
syntax on
set number relativenumber
set cursorline
set cursorcolumn
set expandtab
set tabstop=2
set shiftwidth=2
set noshowcmd
" autocompletion
set wildmenu
set wildmode=longest,list,full
" theme
set termguicolors
colorscheme base16-black-metal-mayhem
" transparent bg
augroup TransparentBG
  autocmd!
  autocmd VimEnter,ColorScheme * call s:TransparentBG()
  autocmd User GoyoEnter call s:TransparentBG()
  autocmd User GoyoLeave call s:TransparentBG()
augroup END
function! s:TransparentBG() abort
  highlight Normal           ctermbg=NONE guibg=NONE
  highlight NormalNC         ctermbg=NONE guibg=NONE
  highlight EndOfBuffer      ctermbg=NONE guibg=NONE
  highlight SignColumn       ctermbg=NONE guibg=NONE
  highlight LineNr           ctermbg=NONE guibg=NONE
  highlight CursorColumn     ctermbg=NONE guibg=NONE
  highlight NormalFloat      ctermbg=NONE guibg=NONE
  highlight FloatBorder      ctermbg=NONE guibg=NONE
  highlight Pmenu            ctermbg=NONE guibg=NONE
  highlight PmenuSel         ctermbg=NONE guibg=NONE
endfunction
" connect mappings
if filereadable(expand('~/dotfiles/vim/mappings.vim'))
	execute 'source' fnameescape(expand('~/dotfiles/vim/mappings.vim'))
endif

