general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = ~/dotfiles/scripts/resume
}

listener {
    timeout = 900
    on-timeout = pgrep -x hyprlock && systemctl suspend
}
