env = XCURSOR_THEME,ComixCursors-Orange
env = XCURSOR_SIZE,30

source = ~/.config/hypr/conf.d/local.conf
source = ~/.config/hypr/conf.d/monitor.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/autostart.conf
source = ~/.config/hypr/conf.d/visuals.conf
