# Black Metal (Immortal) theme
# Colors
bg         = 0x00000000   # immortal bg
fg         = 0x00c1c1c1   # immortal fg
border_fg  = 0x007799bb   # immortal frost
error_bg   = 0x00000000   # immortal bg
error_fg   = 0x015f8787   # immortal teal (bold)

# Clean/minimalist
hide_version_string  = true
hide_keyboard_locks  = true
hide_key_hints       = true
blank_box            = false
box_title            = null
clock                = %H:%M

# Input
asterisk     = •
input_len    = 28
default_input = login
save         = true
session_log  = .local/state/ly-session.log

animation = none
