vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.cursorline = true
vim.opt.cursorcolumn = true
vim.opt.expandtab = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.wildmode = { "longest", "list", "full" }
vim.opt.termguicolors = true
vim.opt.laststatus = 0
