exec-once = awww-daemon
exec-once = sleep 3 && awww img ~/Pictures/greekwp.png
exec-once = $cursor
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = swaync
exec-once = kanshi
exec-once = eww daemon
exec-once = waybar
exec-once = hypridle
exec-once = mpris-proxy
exec-once = ~/dotfiles/scripts/lid-init
