device {
    name = logitech-wireless-mouse-mx-master-3-1
    sensitivity = -0.7
}

input {
    kb_layout = us,ru
    kb_options = ctrl:swapcaps,altwin:swap_alt_win

    touchpad {
        tap-to-click = true
        tap_button_map = lrm
        drag_lock = true
        natural_scroll = false
        disable_while_typing = true
        scroll_factor = 1.0
    }

    accel_profile = adaptive
    sensitivity = -0.1
}
