monitor = eDP-1, 1920x1080@59.98, 0x0, 1.5
monitor = DP-2, 1920x1080@60, 1280x0, 1

bindl = , switch:on:Lid Switch, exec, ~/dotfiles/scripts/lid-close
bindl = , switch:off:Lid Switch, exec, ~/dotfiles/scripts/lid-open
