monitor = eDP-1, 1920x1080@59.98, 0x0, 1
monitor = DP-1, 1920x1080@60, 1920x0, 1
monitor = DP-2, 1920x1080@60, 1920x0, 1

bindl = , switch:on:Lid Switch, exec, ~/dotfiles/scripts/monitor-ctl close
bindl = , switch:off:Lid Switch, exec, ~/dotfiles/scripts/monitor-ctl open
