general {
    gaps_in = 8
    gaps_out = 8
    border_size = 1
}

decoration {
    rounding = 4
    active_opacity = 1
    inactive_opacity = 0.5
}

animations {
    enabled = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
