#!/usr/bin/env bash
set -e
set -u

case "${1:-}" in 
  -h|--help)
    echo "usage: $(basename "$0") [FILE]"
    echo "usage: paste clipboard contents to stdout"
    exit 0
    ;;
esac

if hash pbpaste 2>/dev/null; then
  exec pbpaste
elif hash wl-paste 2>/dev/null; then
	exec wl-paste
elif hash xclip 2>/dev/null; then
  exec xclip -selection clipboard -o
elif [[ -e /tmp/clipboard ]]; then
  exec cat /tmp/clipboard
else
  echo ''
fi

