# main settings
set -g history-limit 50000
set -g default-terminal "tmux-256color"
set -as terminal-features "tmux-256color:RGB"
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
setw -g mode-keys vi
set -g pane-base-index 1
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g repeat-time 500
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "copy"
# plugins
set -g @plugin 'tmux-plugins/tpm'
# status
set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-right-length 100
set -g status-left-length 40
source-file ~/dotfiles/tmux/themes/traffic.conf
# vim movement
bind c new-window -c "$HOME"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %
unbind C-e
# navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# run tpm
run '~/.config/tmux/plugins/tpm/tpm'
