# main settings
set -g history-limit 50000
set -g default-terminal "tmux-256color"
set -as terminal-features "tmux-256color:RGB"
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
set -g mode-keys vi #turn on vim-like hotkeys
set -g pane-base-index 1 #pane numeration from 0 to 1
set -g base-index 1 #window numeration from 0 to 1
set -g mouse on #turn on mouse interaction
set -g repeat-time 500 #time to track same button pressed
# plugins
set -g @plugin 'tmux-plugins/tpm'
# status
set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-right-length 100
set -g status-left-length 40
source-file ~/dotfiles/tmux/themes/guts.conf #color scheme
# vim split
bind | split-window -h -c "#{pane_current_path}" #vertical split
bind - split-window -v -c "#{pane_current_path}" #horizontal split
unbind '"'
unbind %
# window creation
bind c new-window -c "$HOME"
unbind C-e
# navigation between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# copy
bind -T copy-mode-vi v send-keys -X begin-selection #start selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "copy" #copy selection to system clipboard
# resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# scroll history vim-like (no prefix)
# default state
bind -n M-k copy-mode \; send-keys -X scroll-up
bind -n M-j copy-mode \; send-keys -X scroll-down
bind -n M-u copy-mode \; send-keys -X halfpage-up
bind -n M-d copy-mode \; send-keys -X halfpage-down
# vim-mode state
bind -T copy-mode-vi M-k send-keys -X scroll-up
bind -T copy-mode-vi M-j send-keys -X scroll-down
bind -T copy-mode-vi M-u send-keys -X halfpage-up
bind -T copy-mode-vi M-d send-keys -X halfpage-down
# run tpm
run '~/.config/tmux/plugins/tpm/tpm'
