export ZDOTDIR="$HOME/.config/zsh"
export CLAUDE_CONFIG_DIR="$HOME/.config/claude"
export W3M_DIR="$HOME/.local/share/w3m"
export GNUPGHOME="$HOME/.local/share/gnupg"
export BUNDLE_USER_HOME="$HOME/.local/share/bundle"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
