export ZDOTDIR="$HOME/.config/zsh"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

export CLAUDE_CONFIG_DIR="$XDG_CONFIG_HOME/claude"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export W3M_DIR="$XDG_DATA_HOME/w3m"
export BUNDLE_USER_HOME="$XDG_DATA_HOME/bundle"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export ANSIBLE_HOME="$XDG_DATA_HOME/ansible"
export KUBECONFIG="$XDG_CONFIG_HOME/kube/config"
export TELEPORT_LOGIN="devops"
export LESSHISTFILE="$XDG_STATE_HOME/less/history"
export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
export REDISCLI_HISTFILE="$XDG_STATE_HOME/rediscli_history"
