typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs go_version time)
typeset -g POWERLEVEL9K_BACKGROUND=
typeset -g POWERLEVEL9K_FOREGROUND='#a8c4c8'

typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND='#2d6a72'
typeset -g POWERLEVEL9K_CONTEXT_ALWAYS_SHOW=true
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n'
typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='#cc5555'

typeset -g POWERLEVEL9K_DIR_BACKGROUND=
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#3a9aaa'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#2d6a72'
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
typeset -g POWERLEVEL9K_DIR_ROOT_BACKGROUND=
typeset -g POWERLEVEL9K_DIR_ROOT_FOREGROUND='#cc5555'

typeset -g POWERLEVEL9K_VCS_BACKGROUND=
typeset -g POWERLEVEL9K_VCS_FOREGROUND='#2a8855'
typeset -g POWERLEVEL9K_VCS_ROOT_BACKGROUND=
typeset -g POWERLEVEL9K_VCS_ROOT_FOREGROUND='#cc5555'
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
typeset -g POWERLEVEL9K_VCS_MODIFIED_ICON='●'

typeset -g POWERLEVEL9K_STATUS_BACKGROUND=
typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#cc5555'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='#cc5555'

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#aa8844'
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='#3a9aaa'
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false

typeset -g POWERLEVEL9K_GO_VERSION_BACKGROUND=
typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND='#2d6a72'
typeset -g POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true

typeset -g POWERLEVEL9K_SWIFT_VERSION_BACKGROUND=
typeset -g POWERLEVEL9K_SWIFT_VERSION_FOREGROUND='#2d6a72'
typeset -g POWERLEVEL9K_SWIFT_VERSION_PROJECT_ONLY=true

typeset -g POWERLEVEL9K_TIME_BACKGROUND=
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#2d6a72'
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%I:%M %p}'
typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{#3a9aaa}❯%f '
