typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

typeset -g POWERLEVEL9K_BACKGROUND=black
typeset -g POWERLEVEL9K_FOREGROUND='#c1c1c1'

typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND='#5f8787'
typeset -g POWERLEVEL9K_CONTEXT_ALWAYS_SHOW=true
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'

typeset -g POWERLEVEL9K_DIR_BACKGROUND='#b3b3b3'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

typeset -g POWERLEVEL9K_VCS_BACKGROUND='#5f8787'
typeset -g POWERLEVEL9K_VCS_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
typeset -g POWERLEVEL9K_VCS_MODIFIED_ICON='●'

typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{#5f8787}❯%f '
